name: push
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "22"
      - run: npm install
      - run: npm run fmtcheck
      - run: npx tcs --noEmit
      - run: npm test
